FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

COPY pom.xml .
COPY rielarmoryspringboot ./rielarmoryspringboot
COPY rielarmoryangular ./rielarmoryangular

RUN mvn -pl rielarmoryspringboot -am clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=builder /app/rielarmoryspringboot/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]