# Step 1: Build Angular App
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps --prefer-offline
COPY . .
RUN npm run build --prod

# Step 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/rielarmoryangular/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80